# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    name: "xcross-go-starter"                          # 编译后的可执行文件名称
    arch: ""                                # 不填默认当前系统架构，可选：386,amd64,arm,all
    system: ""                             # 不填默认当前系统平台，可选：linux,darwin,windows,all
    mod: "none"                            # 强制指定 Go 用什么模式去查找依赖包
    cgo: 0                                 # 是否开启 CGO，默认是关闭的。如果开启，那么交叉编译可能会有问题。
    packSrc: "resource"                    # 将resource目录打包进可执行文件，静态资源无需单独部署
    packDst: "internal/packed/packed.go"   # 打包后生成的Go文件路径，一般使用相对路径指定到本项目目录中 自动把 packSrc 里的所有文件 → 打包进 packDst 文件
    version: ""                            # 程序版本，如果指定版本信息，那么程序生成的路径中会多一层以版本名称的目录
    output: "./temp/xcross-go-starter"                 # 可执行文件生成路径
    extra: ""
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app